spring:
  datasource:
    url: jdbc:mysql://localhost:3306/docappointmentdb
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: doctor-service
  config:
    import: "optional:configserver:http://localhost:8088"